### ISSUE TITLE
Verticals slides doesn't work

### ISSUE THREAD

**Issue by DanielRamosAcosta** [dluxemburg/reveal-run-in-terminal#1]
When the plugin is used as vertical slides, the code doesn't show up...

**Comment by Riduidel** [comment]
If you want, I'm forking this project to bring back some life in. I'll be very happy to accept your PR at https://github.com/Riduidel/reveal-run-in-terminal

**Comment by DanielRamosAcosta** [comment]
Almost 4 years ago @Riduidel 😂 , let me close this
